config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: "task"
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: "edit_task"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def new
    @tasks = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

end

private

def task_params
  params.require(:task).permit(:title, :details, :completed)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @tasks do |l| %>
  <%= l.label :title %><br>
  <%= l.text_field :title %><br>
  <br>
  <%= l.label :details %><br>
  <%= l.text_field :details %><br>
  <br>
  <%= l.submit %>
<br><br>
 <%= l.check_box :completed %><%= l.label :completed %>

<% end %>
<br>
<%= link_to "back to list", tasks_path()%>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

  <% @tasks.each do |task| %>
  <% if task.completed? %>
  <%= "[X]" %>
  <% else %>
  <%= "[ ]" %>
  <% end %>
  <%= link_to task.title, task_path(task) %>
  <br>
  <% end %>
  <br>
  <%= link_to "add a task", tasks_new_path()%>

app/views/tasks/new.html.erb
<%= form_with model: @tasks do |l| %>
  <%= l.label :title %><br>
  <%= l.text_field :title %><br>
  <br>
  <%= l.label :details %><br>
  <%= l.text_field :details %><br>
  <br><br>
 <%= l.check_box :completed %><%= l.label :completed %>
 <br>
 <%= l.submit %>

<% end %>
<br>
<%= link_to "back to list", tasks_path()%>

app/views/tasks/show.html.erb
<h2><%= @tasks.title %></h2><%= link_to "edit this task", edit_task_path()%>

<p><%= @tasks.details %></p>
<p><%= @tasks.completed %></p>







<%= link_to "back to the list", tasks_path()%>